//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGo.RocketAPI.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokemonGo.RocketAPI.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;root&gt;
        ///  &lt;PtcUsername&gt;
        ///  &lt;/PtcUsername&gt;
        ///  &lt;PtcPassword&gt;
        ///  &lt;/PtcPassword&gt;
        ///  &lt;DefaultLatitude&gt;-33.8589188036947&lt;/DefaultLatitude&gt;
        ///  &lt;DefaultLongitude&gt;151.213339269161&lt;/DefaultLongitude&gt;
        ///  &lt;DefaultAltitude&gt;10&lt;/DefaultAltitude&gt;
        ///  &lt;UseGPXPathing&gt;False&lt;/UseGPXPathing&gt;
        ///  &lt;GPXFile&gt;GPXFILE.gpx&lt;/GPXFile&gt;
        ///  &lt;GPXIgnorePokestops&gt;False&lt;/GPXIgnorePokestops&gt;
        ///  &lt;GPXIgnorePokemon&gt;False&lt;/GPXIgnorePokemon&gt;
        ///  &lt;WalkingSpeedInKilometerPerHour&gt;50&lt;/WalkingSpeedInKilometerPerHour&gt;
        ///  &lt;MaxTravelDistanceInMeters&gt;1000&lt;/MaxT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DefaultSettings {
            get {
                return ResourceManager.GetString("DefaultSettings", resourceCulture);
            }
        }
    }
}
